version: '3.7'
services:
  flaskr:
    image: flaskr
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - flaskr-data:/tmp

  nginx:
    image: nginx:1.16
    ports:
      - 5000:80
    # Add our own nginx configuration file
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - flaskr-data:/tmp

volumes:
  flaskr-data:
