version: '3.7'
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 8080:80
  flaskr:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flaskr
    ports:
      - 5001:5000
