version: '3.7'
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
  flaskr:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flaskr
    networks:
      my-network:
        aliases:
          - flaskr
networks:
  my-network:
